### PR TITLE
Update all dependencies to latest

### PR DESCRIPTION
**Pull request by craigjbass**

### CODE REVIEW

**Comment by adrianclay** [comment]
Does it matter that the lock file still references 2.5.1 ?

https://github.com/homes-england/monitor-api/blob/6dfd1c0d586579cd470dbbe6e318d6f98b543a22/Gemfile.lock#L149

**Comment by ccp92** [comment]
> Does it matter that the lock file still references 2.5.1 ?
> 
> [monitor-api/Gemfile.lock](https://github.com/homes-england/monitor-api/blob/6dfd1c0d586579cd470dbbe6e318d6f98b543a22/Gemfile.lock#L149)
> 
> Line 149 in [6dfd1c0](/homes-england/monitor-api/commit/6dfd1c0d586579cd470dbbe6e318d6f98b543a22)
>  ruby 2.5.1p57

Don't think bundle install had been re-run after updating the ruby version. Commit https://github.com/homes-england/monitor-api/pull/251/commits/cad601bff43746f12273090a68be6751e110ce27 should resolve that.

**Comment by craigjbass** [comment]
Ha I just forced pushed over cad601b shoulda used `--force-with-lease`. Do what I say not what I do people!

**Comment by craigjbass** [comment]
@adrianclay not sure it affects anything, but it's nice to have them match

**Pull request merged**
